### ISSUE TITLE
Generate SE Bracket Error for some sizes

### ISSUE THREAD

**Issue by rgstephens** [karkkant/ngBracket#1]
Try generating a bracket with 14 empty teams using the demoApp Generate feature and you'll find the bracket is generated incorrectly.  There should be two "play-in" rounds.

**Comment by karkkant** [comment]
![image](https://cloud.githubusercontent.com/assets/7612173/9830783/2f0d3eba-5944-11e5-839a-5999575d0fb0.png)

I'm not quite sure what you mean by that. Above is the currently generated rounds and it seems work as intended. Can you draw and link the bracket as you'd expect it to be generated?

**Comment by rgstephens** [comment]
You're right.  I was looking at the bracket wrong.

Thanks,

Greg

**Comment by rgstephens** [comment]
You're right.  I was looking at the bracket wrong.
