### ISSUE TITLE
Demo app Shuffle error

### ISSUE THREAD

**Issue by rgstephens** [karkkant/ngBracket#3]
When I generate a bracket with empty teams in the demo app and then click Shuffle, I get the error:

```
TypeError: Cannot read property '0' of undefined
  at Object.shuffle (http://localhost:9000/src/tournamentGenerator.js:587:39)
```

**Comment by karkkant** [comment]
Thanks I'll look into it. 

Althought I'm not quite sure if that shuffle function should be there in the first place. It's not essential for generating brackets, but more of an optional utility. It would be nice to collect more such functions in a separate stand-alone service.
