### ISSUE TITLE
Server is not a function

### ISSUE THREAD

**Issue by bcrigler** [karkkant/ngBracket#6]
`Brians-MacBook-Pro:ngBracket` `bcrigler$ grunt`
`Running "jshint:files" (jshint) task`
`>> 3 files lint free.`

`Running "karma:unit" (karma) task`
`Warning: Server is not a function Use --force to continue.`

`Aborted due to warnings.`

**Comment by bcrigler** [comment]
I fixed it but you should probably update the repo to use karma@^0.13.0 per this ->

npm WARN grunt-karma@0.12.2 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.

**Comment by karkkant** [comment]
Thanks, dependencies are now updated. Seems that grunt-karma was also missing from configuration.
